### ISSUE TITLE
Errors thrown by use of electron.net.request

### ISSUE THREAD

**Issue by Polarisation** [MarshallOfSound/electron-devtools-installer#42]
Under electron 1.6.2 I tried running `installExtension` in the renderer process, but it threw all sorts of errors which appeared to be related to the use of `electron.net.request` (if I changed https://github.com/MarshallOfSound/electron-devtools-installer/blob/master/src/utils.js#L13 to use `http.request` it worked fine).

I switched to running `installExtension` in the main process in the `app.on('ready'` event handler, that works great.

I'm not sure if there's a bug here regarding the use of `electron.net.request` or if the documentation just needs updating to indicate where to run `installExtension`

**Comment by MarshallOfSound** [comment]
> but it threw all sorts of errors 

Can you post these errors, though I do recommend installing from the main process 👍 

> I switched to running installExtension in the main process in the app.on('ready'

Pretty sure that just needs to be part of the docs now 👍

**Comment by Polarisation** [comment]
Yes, three distinct errors repeated a number of times, about 25 errors in total. As you will see the call stack is not obviously related to `electron-devtools-installer` so it was not that easy to track down. As I previously had `electron-devtools-installer` working on 1.4.x, these errors only occurred after updating Electron and clearing out the application data. 

    TypeError: this.on is not a function
    File "events.js", line 305, col 8, in once
    File "node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js", line 48, col 42, in CallbacksRegistry.apply
    return this.get(id).apply(global, ...args)
    File "node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js", line 283, col 21, in EventEmitter.<anonymous>
    callbacksRegistry.apply(id, metaToValue(args))
    File "events.js", line 116, col 13, in emitThree
    File "events.js", line 194, col 7, in EventEmitter.emit


    TypeError: Cannot read property 'ended' of undefined
    File "_stream_writable.js", line 241, col 12, in Writable.write
    File "node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js", line 48, col 42, in CallbacksRegistry.apply
    return this.get(id).apply(global, ...args)
    File "node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js", line 283, col 21, in EventEmitter.<anonymous>
    callbacksRegistry.apply(id, metaToValue(args))
    File "events.js", line 116, col 13, in emitThree
    File "events.js", line 194, col 7, in EventEmitter.emit


    TypeError: Cannot read property 'corked' of undefined
    File "_stream_writable.js", line 481, col 12, in Writable.end
    File "node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js", line 48, col 42, in CallbacksRegistry.apply
    return this.get(id).apply(global, ...args)
    File "node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js", line 283, col 21, in EventEmitter.<anonymous>
    callbacksRegistry.apply(id, metaToValue(args))
    File "events.js", line 116, col 13, in emitThree
    File "events.js", line 194, col 7, in EventEmitter.emit

**Comment by MarshallOfSound** [comment]
@Polarisation Dayum, I had those errors on one machine a few weeks back but couldn't figure out what was causing it.  Guess it was `net` working from the renderer process causing the issues on a machine that hadn't used Electron before.  Will investigate that issue upstream 👍

**Comment by rkpatel33** [comment]
+1 Same errors.

**Comment by NikhilMutkekar** [comment]
+1 Same errors

**Comment by comatory** [comment]
+1 Same errors, attempts to download file and will get the extension file but it has zero bytes

**Comment by comatory** [comment]
So is there any update on this? For now I had to come with my own solution but it'd be neat if it could be fixed. I'm not getting dev tools installed at all.

**Comment by mbaer3000** [comment]
Same error here

**Comment by karlitos** [comment]
I am also affected by this 😞

**Comment by mckenzieja** [comment]
I'm unsure on where to place the installExtension method.

**Comment by MarshallOfSound** [comment]
Future versions of `electron-devtools-installer` will only be usable from the main process as that's where these APIs are supposed to be called
